name: thundercats

on: push

jobs:
  tygra:
    name: scratch code-base
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo 'Hello All'
        
      - name: Run thundercats
        uses: github/javaapp-opstree
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
